#! /bin/sh /usr/share/dpatch/dpatch-run
## 03_lp-solve_link_shared.dpatch by  <rene@debian.org>
##
## All lines beginning with `## DP:' are a description of the patch.
## DP: No description.

@DPATCH@
diff -urNad lp-solve-5.5.0.10~/demo/ccc lp-solve-5.5.0.10/demo/ccc
--- lp-solve-5.5.0.10~/demo/ccc	2007-01-22 03:06:09.000000000 +0100
+++ lp-solve-5.5.0.10/demo/ccc	2007-01-22 03:06:32.000000000 +0100
@@ -1,4 +1,3 @@
-src='../lp_MDO.c ../shared/commonlib.c ../shared/mmio.c ../shared/myblas.c ../ini.c ../lp_rlp.c ../lp_crash.c ../bfp/bfp_LUSOL/lp_LUSOL.c ../bfp/bfp_LUSOL/LUSOL/lusol.c ../lp_Hash.c ../lp_lib.c ../lp_wlp.c ../lp_matrix.c ../lp_mipbb.c ../lp_MPS.c ../lp_params.c ../lp_presolve.c ../lp_price.c ../lp_pricePSE.c ../lp_report.c ../lp_scale.c ../lp_simplex.c ../lp_SOS.c ../lp_utils.c ../yacc_read.c'
 c=cc
 
 math=-lm
@@ -12,4 +11,4 @@
 
 opts='-O3'
 
-$c -I.. -I../bfp -I../bfp/bfp_LUSOL -I../bfp/bfp_LUSOL/LUSOL -I/usr/include/suitesparse -I../shared $opts $def -DYY_NEVER_INTERACTIVE -DPARSER_LP -DINVERSE_ACTIVE=INVERSE_LUSOL -DRoleIsExternalInvEngine demo.c $src -o demo $math $dl -lcolamd
+$c -I.. -I../bfp -I../bfp/bfp_LUSOL -I../bfp/bfp_LUSOL/LUSOL -I/usr/include/suitesparse -I../shared $opts $def -DYY_NEVER_INTERACTIVE -DPARSER_LP -DINVERSE_ACTIVE=INVERSE_LUSOL -DRoleIsExternalInvEngine demo.c -o demo $math $dl -lcolamd -L../lpsolve55 -llpsolve55 -Wl,-rpath=/usr/lib/lp_solve
diff -urNad lp-solve-5.5.0.15~/lp_solve/ccc lp-solve-5.5.0.15/lp_solve/ccc
--- lp-solve-5.5.0.15~/lp_solve/ccc	2007-01-22 03:06:09.000000000 +0100
+++ lp-solve-5.5.0.15/lp_solve/ccc	2007-01-22 03:06:11.000000000 +0100
@@ -1,5 +1,5 @@
 :
-src='../lp_MDO.c ../shared/commonlib.c ../shared/mmio.c ../shared/myblas.c ../ini.c ../fortify.c ../lp_rlp.c ../lp_crash.c ../bfp/bfp_LUSOL/lp_LUSOL.c ../bfp/bfp_LUSOL/LUSOL/lusol.c ../lp_Hash.c ../lp_lib.c ../lp_wlp.c ../lp_matrix.c ../lp_mipbb.c ../lp_MPS.c ../lp_params.c ../lp_presolve.c ../lp_price.c ../lp_pricePSE.c ../lp_report.c ../lp_scale.c ../lp_simplex.c lp_solve.c ../lp_SOS.c ../lp_utils.c ../yacc_read.c'
+src="lp_solve.c"
 c=cc
 
 #determine platform (32/64 bit)
@@ -38,4 +38,4 @@
 else dl=-ldl
 fi
 
-$c -I.. -I../bfp -I../bfp/bfp_LUSOL -I../bfp/bfp_LUSOL/LUSOL -I/usr/include/suitesparse -I../shared $opts $def $NOISNAN -DYY_NEVER_INTERACTIVE -DPARSER_LP -DINVERSE_ACTIVE=INVERSE_LUSOL -DRoleIsExternalInvEngine $src -o bin/$PLATFORM/lp_solve $math $dl -lcolamd
+$c -I.. -I../bfp -I../bfp/bfp_LUSOL -I../bfp/bfp_LUSOL/LUSOL -I/usr/include/suitesparse -I../shared $opts $def $NOISNAN -DYY_NEVER_INTERACTIVE -DPARSER_LP -DINVERSE_ACTIVE=INVERSE_LUSOL -DRoleIsExternalInvEngine $src -o bin/$PLATFORM/lp_solve $math $dl -lcolamd -L../lpsolve55/bin/$PLATFORM -llpsolve55 -Wl,-rpath=/usr/lib/lp_solve
